## Creating  Array

In [4]:
import numpy as np
print(np.array([[1,2,3,4],[2,3,4,5]]))
print(np.zeros((2,3)))
print(np.arange(20))
print(np.linspace(1,10,10,dtype=np.int64))
print(np.random.rand(4,3))
print(np.random.randn(4,3))
print(np.random.randint(2,10,(3,4)))
y=np. full((4,3),100)
print(y)
y=np.diag([1,2,3],k=0)
print (y)
print(np.diag(y,k=0))
print("empty")
print(np.empty((3,3),dtype=np.int64))

print(np.diag(y,k=0))

[[1 2 3 4]
 [2 3 4 5]]
[[0. 0. 0.]
 [0. 0. 0.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  2  3  4  5  6  7  8  9 10]
[[0.11031806 0.13623564 0.61744822]
 [0.28217115 0.87666397 0.27844362]
 [0.83741323 0.15487538 0.81356399]
 [0.33052502 0.64479822 0.67542197]]
[[ 1.038569   -1.30852087 -0.19395457]
 [-0.2220904  -0.314203   -1.15157203]
 [-0.26887471  1.47413241 -1.67800911]
 [ 0.52655492  0.19272258 -0.54963547]]
[[9 4 2 8]
 [7 7 8 5]
 [5 8 8 3]]
[[100 100 100]
 [100 100 100]
 [100 100 100]
 [100 100 100]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[1 2 3]
empty
[[                0                 0                 0]
 [                0                 0              1316]
 [14355640424071168 27584998689210368 19140642018951168]]
[1 2 3]


In [5]:
np.save("array",np.empty((2,3)))

In [6]:
y=np.load("array.npy")
print(y)

[[2.12199579e-312 2.12199579e-312 2.12199579e-312]
 [2.12199579e-312 2.12199579e-312 2.12199579e-312]]


### Deleting ,Appending and Inserting elements to ndarrays

In [7]:
print(np.delete(y,2,axis=1)) #delete the third row from Y

[[2.12199579e-312 2.12199579e-312]
 [2.12199579e-312 2.12199579e-312]]


In [9]:

print(np.append(y,[[1],[2]],axis=1)) # append accepts list with the same dimension 
print('\n\n',y)

[[2.12199579e-312 2.12199579e-312 2.12199579e-312 1.00000000e+000]
 [2.12199579e-312 2.12199579e-312 2.12199579e-312 2.00000000e+000]]


 [[2.12199579e-312 2.12199579e-312 2.12199579e-312]
 [2.12199579e-312 2.12199579e-312 2.12199579e-312]]


In [10]:
print(np.insert(y,1,[1,2,3],axis=0)) #but insert accepts list with same number of as the row or column

[[2.12199579e-312 2.12199579e-312 2.12199579e-312]
 [1.00000000e+000 2.00000000e+000 3.00000000e+000]
 [2.12199579e-312 2.12199579e-312 2.12199579e-312]]


### Slicing and Reshaping 

In [11]:
x=np.arange(1,5)
print(x)
print(x[::-1])
print(x.reshape((2,2))[::-1,::-1])
print(x)


[1 2 3 4]
[4 3 2 1]
[[4 3]
 [2 1]]
[1 2 3 4]


### Concatenation and splitting

In [18]:
x=np.array([3,4,5,6])
y=np.array([1,3,4,6])
print(np.concatenate([[x],[y]]))
print(np.concatenate([x,y]))
x=np.arange(10).reshape((2,5))
y=np.arange(10,20).reshape((2,5))
print(np.concatenate([x,y],axis=0))

[[3 4 5 6]
 [1 3 4 6]]
[3 4 5 6 1 3 4 6]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [19]:
print(np.vstack([x,y]))
print(np.hstack([x,y]))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4 10 11 12 13 14]
 [ 5  6  7  8  9 15 16 17 18 19]]


In [21]:
z=np.vstack([x,y])
print(z)
print(np.split(z,[1,3],axis=0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[array([[0, 1, 2, 3, 4]]), array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19]])]


In [22]:
x=np.arange(1,26).reshape([5,5])
print(x%2!=0)
y=x[x%2!=0]
print(y)

[[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


# Transpose and swap axis

In [25]:
print(np.transpose(x))
print(x.swapaxes(0,1))
print(x.T)
print(x)

[[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]
[[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]
[[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


# Boolean indexing

In [26]:
y=np.array([1,2,3,4])
print(y>2)
print(y[y>2])

[False False  True  True]
[3 4]


# fancy indexing
fancy indexing used when we want to use array as an index.The resulting array has the same dimension as that of the index.<br>
let x=np.arange(20)

ind=np.array([3,4,7])

x[ind]=[x(3),x[4],x[7]]

when we index array with list it works like matlab but when we idex it with array it retuns the same size like the idexing array.

In [37]:
x=np.arange(20)
ind=np.array([[2,1,0],[1,3,2]])
print(x[ind])

ind=np.array([3,4,7])
print(x[ind])
ind=([1,2,3],[1,2,3])
print(x.reshape((4,5)))
print(x.reshape((4,5))[ind])

[[2 1 0]
 [1 3 2]]
[3 4 7]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 6 12 18]


# Universal functions

### Arithmetic functions

In [38]:
x=np.arange(1,10).reshape(3,3)
y=np.arange(10,19).reshape(3,3)
print(np.add(x,y),x+y,sep="\n")
print("\n",np.subtract(x,y),x-y,sep='\n')
print(np.floor_divide(x,y),x//y ,sep="\n")
print(np.power(x,y),x**y,sep="\n")

[[11 13 15]
 [17 19 21]
 [23 25 27]]
[[11 13 15]
 [17 19 21]
 [23 25 27]]


[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]
[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[          1        2048      531441]
 [   67108864  1808548329  2033549312]
 [-1526366847           0 -1953380655]]
[[          1        2048      531441]
 [   67108864  1808548329  2033549312]
 [-1526366847           0 -1953380655]]


### rounding and sign methods

In [39]:
print(np.sign(x))
print(np.rint(np.random.rand(2,3)))
print(np.ceil(np.random.rand(2,3)))

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]


### Expressing conditional logic

where method return an array depending on the condition if true place an element at the given point from array 1 else place an element from array2.The size of the resulting array and the size the condition are the same.

In [40]:
print(x)
print(np.where(x>7,2,y))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16  2  2]]


### Mathematical and statistical methods

In [55]:
y=np.random.randn(5,4)
print(y)
print(np.sum(y,axis=1))
print(y.sum(axis=0))

[[ 0.18371416 -0.80009026 -0.6895769   0.48066235]
 [-0.73248374  0.33327635  0.12033958  0.05522773]
 [-0.54203842  1.13991475  0.2873645   1.57001958]
 [-1.91157806 -0.86078664  0.8804048  -1.68319608]
 [ 0.94596876  0.58718897 -2.80835785 -0.44819043]]
[-0.82529065 -0.22364008  2.45526041 -3.57515598 -1.72339055]
[-2.0564173   0.39950316 -2.20982589 -0.02547684]


### Methods for Boolean arrays

In [41]:
y=np.random.randn(20)
print((y>0).all())
print((y>-0.3).any())

False
True


### sorting
sort method returns none
i.e it changes the array

In [75]:
x=np.random.randint(0,10,(5,4))
print(x)
x.sort(axis=0)
print(x)

[[0 6 1 0]
 [6 7 8 0]
 [1 5 0 7]
 [6 7 8 6]
 [3 0 5 7]]
[[0 0 0 0]
 [1 5 1 0]
 [3 6 5 6]
 [6 7 8 7]
 [6 7 8 7]]


In [ ]:
print(np.delete(x,[1],axis=0))

In [85]:
y=np.diag([1,2,3])
y.sort(0)
print(y)

[[0 0 0]
 [0 0 0]
 [1 2 3]]


In [86]:
z=np.arange(1,5)
y=np.zeros((4,4),dtype=np.int16)

print(z+y)
k=y[0,0]
k=k+34
print(k)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
34


In [87]:
x=np.random.randint(0,20,[3,4])

In [103]:
print(x.mean(0).shape)
print(x-x.mean(0))

(4,)
[[  9.33333333 -11.66666667   6.66666667   2.66666667]
 [ -5.66666667   5.33333333  -2.33333333  -2.33333333]
 [ -3.66666667   6.33333333  -4.33333333  -0.33333333]]


In [92]:
ind=np.random.permutation(3)
print(ind)
print(x[ind,ind])

[1 0 2]
[18 17  3]


# Broadcasting rules

In [42]:
x=np.random.randint(0,30,(4,4))
print(x)
print(x[:,:,np.newaxis])
z=np.arange(10)
print(z.shape)
print(z[:,np.newaxis])


[[10  2 22  2]
 [11 20  1 16]
 [20  4 24 13]
 [19  0 29 16]]
[[[10]
  [ 2]
  [22]
  [ 2]]

 [[11]
  [20]
  [ 1]
  [16]]

 [[20]
  [ 4]
  [24]
  [13]]

 [[19]
  [ 0]
  [29]
  [16]]]
(10,)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [43]:
y=np.arange(1,5)
x[:]=y[:]
print(x)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
